# Data Preprocessing Tools

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv') # Importing the dataset
x = dataset.iloc[:, :-1].values #.iloc[rows, columns]  and values returns a matrix from the dataset, a numpy matrix  loc is names of columns!
y = dataset.iloc[:, -1].values





In [3]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer  #out strategy is to replace the missing data with the mean
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')  #missing value are the numpy nan values and strategy is to replace the missing data with the mean
imputer.fit(x[:, 1:3]) #finds mean and nan values the ones with numerical values, all the rows, and columns 1 and 2, the only rows that are numbers
x[:, 1:3] = imputer.transform(x[:, 1:3]) #replaces the missing data with the mean, basically this method returns 2 lists, to replace the missing data with the mean
print(x)



[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [6]:
from sklearn.compose import ColumnTransformer #the actual class that doe the transformation
from sklearn.preprocessing import OneHotEncoder #the type of transformations
#these are used in tandom to transform categorical data into numerical data
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough') #[(type of trasformation, tool to use, and indexes)]
# remainder to indicate which columns to keep, passthrough to keep everything else
x = np.array(ct.fit_transform(x))  #fit_transform which fits and then transforms, fit_transform with onehotencoder does not return a numpy array
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [7]:
from sklearn.preprocessing import LabelEncoder #used to transform categorical data into numerical data, good for binary data
le = LabelEncoder() #obvious in what needs to be encoded since it is binary
y = le.fit_transform(y) #fit_transform which fits and then transforms, this does not need to be a numpy array
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1) #arguments the indepdendent vars
#the dependent vars, the percentage of the data to be used for training and the random state is for randomization

In [9]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [10]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [11]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [12]:
print(y_test)

[0 1]


## Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #create and object of the class
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:]) #fit and transform according to training data
x_test[:, 3:] = sc.transform(x_test[:, 3:]) #just transform test, according to how it was it was fit with the tese data


In [14]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [15]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
