# Artificial Neural Network

### Importing the libraries

In [35]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.17.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [44]:
dataset = pd.read_csv("./Churn_Modelling.csv")
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [58]:
X = dataset.iloc[:, 3:-1].values
y = dataset['Exited'].values

In [50]:
X[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Encoding categorical data

In [51]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

Label Encoding the "Gender" column

In [59]:
from sklearn.preprocessing import LabelEncoder
l_encoder = LabelEncoder()
X[:, 2] = l_encoder.fit_transform(X[:, 2])


In [41]:
X[0]

array([619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

One Hot Encoding the "Geography" column

In [60]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("encoder", OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

X[0]


array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)



### Feature Scaling

In [64]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)




## Part 2 - Building the ANN

### Initializing the ANN

In [70]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [71]:
#input layer will have 1 node per input, added auromatically by Keras
#dence class makes it fully connected with previous layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #adding a fully connected layer with 6 neurons and relu activation function

### Adding the second hidden layer

In [72]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #adding a fully connected layer with 6 neurons and relu activation function

### Adding the output layer

In [73]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #probabilities as well

## Part 3 - Training the ANN

### Compiling the ANN

In [74]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']) # adam for stochastic gd, binary_crossentropy for binary classification

### Training the ANN on the Training set

In [76]:
ann.fit(X_train, y_train, batch_size=32, epochs=100) #batch size is 32, epochs is 100

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8632 - loss: 0.3367
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8642 - loss: 0.3384
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8661 - loss: 0.3322
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8681 - loss: 0.3282
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8688 - loss: 0.3246
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8599 - loss: 0.3454
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8711 - loss: 0.3195
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8625 - loss: 0.3304
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3340
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3347
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8588 - loss: 0.3419
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [84]:
pred = (ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60_000, 2, 1, 1, 50_000]])) > 0.5) # > is item wise comparison, returns boolean array
pred



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[False]])

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [89]:
y_pred = (ann.predict(X_test) > 0.5).astype(int).flatten() #predicting on test set
y_pred


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


array([0, 0, 0, ..., 0, 0, 0])

In [90]:
data = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred}) 
data

Actual  Predicted
0          0          0
1          1          0
2          0          0
3          0          0
4          0          0
...      ...        ...
1995       0          0
1996       0          0
1997       0          0
1998       0          0
1999       0          0

[2000 rows x 2 columns]

### Making the Confusion Matrix

In [95]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = pd.DataFrame(confusion_matrix(y_test, y_pred), index=['Not Exited', 'Exited'], columns=['Predicted Not Exited', 'Predicted Exited']) 
cm

Predicted Not Exited  Predicted Exited
Not Exited                  1509                86
Exited                       201               204

In [96]:
accuracy_score(y_test, y_pred)

0.8565